import {
  IconActivityHeartbeat,
  IconBackpack,
  IconBomb,
  IconBook,
  IconBrandFunimation,
  IconDeviceTvOld,
  IconExclamationMark,
  IconGhost2,
  IconHeart,
  IconLasso,
  IconMusic,
  IconQuestionMark,
  IconRobot,
  IconShield,
  IconSkull,
  IconTower,
  IconUsersGroup,
  IconVideo,
  IconXd,
} from '@tabler/icons-react';

export const categoryIcons = {
  accion: <IconSkull size={20} />,
  aventura: <IconBackpack size={20} />,
  animacion: <IconBrandFunimation size={20} />,
  comedia: <IconXd size={20} />,
  crimen: <IconShield size={20} />,
  documental: <IconVideo size={20} />,
  drama: <IconExclamationMark size={20} />,
  familia: <IconUsersGroup size={20} />,
  fantasia: <IconTower size={20} />,
  historia: <IconBook size={20} />,
  terror: <IconGhost2 size={20} />,
  musica: <IconMusic size={20} />,
  misterio: <IconQuestionMark size={20} />,
  romance: <IconHeart size={20} />,
  ciencia_ficcion: <IconRobot size={20} />,
  pelicula_de_tv: <IconDeviceTvOld size={20} />,
  suspense: <IconActivityHeartbeat size={20} />,
  belica: <IconBomb size={20} />,
  western: <IconLasso size={20} />,
};
