import {
  IconActivityHeartbeat,
  IconAlien,
  IconBackpack,
  IconBomb,
  IconBook,
  IconBrandFunimation,
  IconCircleLetterS,
  IconDeviceTvOld,
  IconExclamationMark,
  IconGhost2,
  IconHeart,
  IconHorseToy,
  IconLasso,
  IconMan,
  IconMicrophone2,
  IconMusic,
  IconNews,
  IconQuestionMark,
  IconRobot,
  IconShield,
  IconSkull,
  IconSword,
  IconTower,
  IconUsersGroup,
  IconVideo,
  IconXd,
} from '@tabler/icons-react';

export const categoryIcons = {
  accion: <IconSkull size={20} />,
  'action_&_adventure': <IconSkull size={20} />,
  'sci-fi_&_fantasy': <IconAlien size={20} />,
  "war_&_politics": <IconSword size={20} />,
  soap: <IconCircleLetterS size={20} />,
  talk: <IconMicrophone2 size={20} />,
  kids: <IconHorseToy size={20} />,
  news: <IconNews size={20} />,
  reality: <IconMan size={20} />,
  aventura: <IconBackpack size={20} />,
  animacion: <IconBrandFunimation size={20} />,
  comedia: <IconXd size={20} />,
  crimen: <IconShield size={20} />,
  documental: <IconVideo size={20} />,
  drama: <IconExclamationMark size={20} />,
  familia: <IconUsersGroup size={20} />,
  fantasia: <IconTower size={20} />,
  historia: <IconBook size={20} />,
  terror: <IconGhost2 size={20} />,
  musica: <IconMusic size={20} />,
  misterio: <IconQuestionMark size={20} />,
  romance: <IconHeart size={20} />,
  ciencia_ficcion: <IconRobot size={20} />,
  pelicula_de_tv: <IconDeviceTvOld size={20} />,
  suspense: <IconActivityHeartbeat size={20} />,
  belica: <IconBomb size={20} />,
  western: <IconLasso size={20} />,
};
